#!/data/data/com.termux/files/usr/bin/bash
#
# This is a termux-url-opener script to do diffrent tasks on my Android phone 
#
#
#
# How to use this script
#############################
# 
# Install git
# ➜ ~ pkg install git
# 
# clone this script
# ➜ ~ git clone https://gist.github.com/dc35e8df3dc41d126683f18fe44ebe17.git $HOME/termux-url-opener
#
# Create the bin directory
# ➜ ~ mkdir bin
#
# Link the script
# ➜ ~ ln -s $HOME/termux-url-opener/.my-termux-url-opener $HOME/bin/termux-url-opener
# ➜ ~ ln -s $HOME/termux-url-opener/.my-termux-url-opener $HOME/bin/termux-file-editor
# 
# run the following command to enable the termux storage features
# ➜ termux-setup-storage
# 
# https://wiki.termux.com/wiki/Termux-setup-storage
#
# the script downloads the needed tools on first use.


url=$1
echo "What should I do with $url ?"
echo "1) yt-dlp no-config "
echo "2) yt-dlp audio "
echo "3) yt-dlp split audio "
echo "4) yt-dlp 480 "
echo "7) yt-dlp 720 "
echo "0) yt-dlp mp3 "
echo "g) gallery-dl"
# echo "y) download youtube video to movies-folder"
# echo "u) download youtube video and convert it to mp3 (music-folder)"
# echo "s) download with scdl (soundcloud)"
# echo "t) download torrent"
echo "a) download aria2c"
# echo "w) wget file to download-folder" 
echo "z) nothing"

read CHOICE
case $CHOICE in
  1)
    yt-dlp --no-config --no-mtime --restrict-filenames -o "/storage/emulated/0/ytdlp/video/%(webpage_url_domain)s/%(title)s_[%(id)s].%(ext)s" $url
    ;;

  2)
    yt-dlp --x $url
    ;;

  3)
    yt-dlp --xpl $url
    ;;

  4)
    yt-dlp --4 $url
    ;;

  7)
    yt-dlp --7 $url
    ;;

  0)
    yt-dlp --xx $url
    ;;

  g)
    gallery-dl $url
    ;;

#  s)
#    scdl -l $url --path /storage/emulated/0/Music
#    echo "s need some work"
#    ;;
  
#  w)
#    cd ~/storage/downloads
#    wget $url
#    ;;
  
#  t)
#    echo "running torrents"
#    transmission-remote 127.0.0.1 -l
#    if [ ! $? eq 0 ]; then # start daemon if necessary
#      transmission-daemon
#      sleep 3
#    fi
#    echo "use transmission-remote to manage your downloads (read the manpage)"
#    transmission-remote 127.0.0.1 -a $(cat $url) 
#    ;;
    
  a)
    aria2c --seed-time=0 -d "/storage/emulated/0/Downloads" $url
    ;;

  z)
    echo "bye"
    ;; 
  esac
